---

networks:
  bobik:

services:
  motivation-frontend:
    container_name: motivation-frontend
    build:
      context: ./bobik-motivation-front
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    depends_on:
      - motivation-backend
    networks:
      - bobik

  motivation-backend:
    container_name: motivation-backend
    build:
      context: ./manager_motivation
      dockerfile: Dockerfile
    command: python manage.py runserver localhost:8000
    volumes:
      - ./manager_motivation/:/code:delegated
    ports:
      - "18080:8000"
    networks:
      - bobik
  
  postgres:
    image: postgres:16.6-alpine
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=bobik-motivator
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - bobik