---

networks:
  bobik:

services:
  postgres:
    image: postgres:16.6-alpine
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=bobik-motivator
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=postgres
    networks:
      - bobik