# Generated by Django 5.1.3 on 2024-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0003_alter_clients_options_alter_deals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='fillial',
            field=models.CharField(blank=True, db_column='fillial', max_length=50, null=True, verbose_name='Филлиал'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Директор филиала', 'Директор филиала'), ('Генеральный директор', 'Генеральный директор')], db_column='name', max_length=50, verbose_name='Название роли'),
        ),
    ]
