# Generated by Django 5.1.3 on 2024-11-30 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0004_alter_roles_fillial_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.DecimalField(db_column='percent', decimal_places=3, max_digits=4, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Процент'),
        ),
    ]
