# Generated by Django 5.1.3 on 2024-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0006_alter_product_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='sum_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='deals',
            name='sum',
            field=models.DecimalField(db_column='sum', decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=12, verbose_name='Стоимость'),
        ),
    ]
